version: '3.8'
services:
  geesefs:
    container_name: geesefs
    image: proorc/geesefs:0.30.5
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    devices:
      - /dev/fuse
    volumes:
      - './bucket:/opt/geesefs/bucket:rshared'
    environment:
      AWS_S3_BUCKET: '${AWS_S3_BUCKET}'
      AWS_S3_ACCESS_KEY_ID: '${AWS_S3_ACCESS_KEY_ID}'
      AWS_S3_SECRET_ACCESS_KEY: '${AWS_S3_SECRET_ACCESS_KEY}'
      AWS_S3_AUTHFILE: '${AWS_S3_AUTHFILE}'
      AWS_S3_SECRET_ACCESS_KEY_FILE: '${AWS_S3_SECRET_ACCESS_KEY_FILE}'
      AWS_S3_URL: '${AWS_S3_URL}'
      AWS_S3_MOUNT: '/opt/geesefs/bucket'
      GEESEFS_ARGS: ''
      GEESEFS_DEBUG: 0
      UID: 1000
      GID: 1000
